avatar: /static/avatar.jpg # ç½‘ç«™ Logo
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
  path: /static/background.jpg
  width: 1440
  height: 960
favicon:
  href: /static/favicon.ico # ç½‘ç«™å›¾æ ‡
  type: image/x-icon # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # åŠŸèƒ½å¼€å…³ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  globalToc: true # å¼€å¯è¯¥åŠŸèƒ½ä¼šè‡ªåŠ¨å¼€å¯æ–‡ç«  TOCï¼ˆæ–‡ç« ç›®å½•ï¼‰ åŠŸèƒ½
  wordCount: true  # æ˜¯å¦å¼€å¯æ–‡ç« å­—æ•°ç»Ÿè®¡ (true, false)
  copyCode: true # æ˜¯å¦å…è®¸å¤åˆ¶ä»£ç å—

imageCDN: # å›¾ç‰‡ CDN åŠŸèƒ½
  enable: false # å¼€å¯è¯¥åŠŸèƒ½  
  # origin: '/static/' # å›¾ç‰‡åŸå§‹ç›®å½•
  # to: https://cdn.jsdelivr.net/gh/wangerzi/blog@latest/source/static/ # å›¾ç‰‡ CDN åŸŸå

cdn: # è¿™é‡Œå¯ä»¥ä¿®æ”¹ç«™ç‚¹ä½¿ç”¨çš„åº“çš„CDN
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    # css: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.css
    # js: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
    css: /static/libs/gitalk.min.css
    js: /static/libs/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine
  mdui:
    # js: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/js/mdui.min.js?v=mine
    js: /static/libs/mdui.min.js
  jquery:
    # js: https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js?v=mine
    js: /static/libs/jquery.min.js
  fancybox:
    # css: https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css?v=mine
    # js: https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js?v=mine
    css: /static/libs/fancybox.css
    js: /static/libs/fancybox.umd.js
  justifiedGallery:
    # js: https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js?v=mine
    # css: https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css?v=mine
    css: /static/libs/justifiedGallery.min.css
    js: /static/libs/jquery.justifiedGallery.min.js

# è‡ªå®šä¹‰æ ·å¼ï¼Œå¯ç”¨åå¯åœ¨ç«™ç‚¹çš„sourceæ–‡ä»¶å¤¹ä¸‹æ–°å»ºcustom.cssè‡ªå®šä¹‰ç«™ç‚¹æ ·å¼
customStyles:
  - custom.css
  
# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
  å›åˆ°é¦–é¡µ: 
    - /
    - icon-home
  æ–‡ç« å½’æ¡£:  # ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/article/archive
    - /archive.html
    - icon-container
  å…³äºåšä¸»:
    - /about.html
    - icon-info-circle
  æˆ‘çš„æœ‹å‹: 
    - /friends.html # ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/article/py

jsonContent:
  meta: false
  pages: false
  posts:
    title: true 
    date: false 
    path: true 
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: false
widgets:
    - name: search
      enable: true
      options: 
        search: 
            type: local # å¯é€‰engineï¼ˆç”¨æœç´¢å¼•æ“æœç´¢ï¼‰ã€swiftypeã€æˆ–localï¼ˆæœ¬åœ°æœç´¢ï¼‰
            url: https://cn.bing.com/search?q=site:nexmoe.com # æœç´¢å¼•æ“åœ°å€ï¼Œåœ¨typeä¸ºswiftypeæ—¶æ— æ•ˆ e.g:https://www.google.com/search?q={ä½ çš„åšå®¢é“¾æ¥}
            id: <swiftype-id> # swiftypeçš„idï¼Œè§å¯ç”¨æ•™ç¨‹ã€‚åœ¨typeä¸ºengineæ—¶æ— æ•ˆ
    - name: social
      enable: true
      options: 
        social:
            # QQç¾¤:
            #     - https://jq.qq.com/?_wv=1027&k=5CfKHun
            #     - icon-QQ
            #     - rgb(249, 174, 8)
            #     - rgba(249, 174, 8, .1)
            # å“”å“©å“”å“©:
            #     - https://space.bilibili.com/20238211
            #     - icon-bilibili
            #     - rgb(231, 106, 141)
            #     - rgba(231, 106, 141, .1)
            GitHub:
                - https://github.com/wangerzi/
                - icon-github
                - rgb(25, 23, 23)
                - rgba(25, 23, 23, .1)
            # çŸ¥ä¹:
            #     - https://www.zhihu.com/people/nexmoe
            #     - icon-zhihu
            #     - rgb(30, 136, 229)
            #     - rgba(30, 136, 229, .1)
            # Twitter:
            #     - https://twitter.com/nexmoe
            #     - icon-twitter
            #     - rgb(59, 151, 239)
            #     - rgba(59, 151, 239, .1)
            RSS:
                - /atom.xml
                - icon-rss
                - rgb(247, 132, 34)
                - rgba(247, 132, 34, .1)
    - name: category
      enable: true
    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 20  # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶
    # - name: hitokoto # ä¸€è¨€ widget
    #   enable: false
    #   options: 
    #     widgetHitokoto: # ä¸€è¨€ç»„ä»¶
    #         loading_placeholder: 'ğŸš€ è·å–ä¸­...' # æ­£åœ¨ä¸€è¨€æ—¶çš„å ä½ç¬¦
    #         loading_error_placeholder: 'ğŸ è·å–å¤±è´¥...' # åŠ è½½ä¸€è¨€å¤±è´¥æ—¶çš„å ä½ç¬¦
    #         category: # ä¸€è¨€å¥å­ç±»å‹ï¼ˆå¯é€‰ï¼‰ï¼Œä¸é…ç½®çš„è¯éšæœºè·å–ï¼Œè¯¦è§ https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #æ–‡ç« å½’æ¡£ç»„ä»¶
            archive_type: 'year' #æŒ‰æœˆå±•ç¤ºè¿˜æ˜¯æŒ‰å¹´å±•ç¤º
            show_count: true  #æ˜¯å¦å±•ç¤ºæ•°é‡
    - name: recent_posts
      enable: true
    # - name: link #settings: widgetLink
    #   enable: true
    #   options: 
    #     widgetLink: #é“¾æ¥ç»„ä»¶
    #         - title: å°èˆ’åŒå­¦
    #           img: https://xsm.nexmoe.com/images/Infinite/Snipaste_2022-05-18_20-46-50.png
    #           link : https://xiaoshu.app/
    #         - title: æŠ˜å½±è½»æ¢¦
    #           img: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/avatar.png
    #           link : https://nexmoe.com/

copyTip: "è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚\nå•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚\næ¥æºï¼š%url" # è‡ªå®šä¹‰å¤åˆ¶ç‰ˆæƒæ–‡æ¡ˆ,ä½¿ç”¨ %url ä»£æ›¿å½“å‰é¡µé¢URL, ä¿®æ”¹ä¸ºfalseç¦ç”¨

slotHead: | 
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZHH2NFM6CG"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "G-ZHH2NFM6CG");
  </script>
# slotFooter: | 
#   <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2058306854838448" crossorigin="anonymous"></script>
# è‡ªå®šä¹‰ä¾§è¾¹æ å°¾éƒ¨å†…å®¹
slotSidebar: |
  <br><a target="_blank" href="https://beian.miit.gov.cn/">æ¸ICPå¤‡17009771å·-1</a>
# è¯„è®ºæ¡†æ’æ§½
slotComment: | 
  è¯·åœ¨ä½ çš„é…ç½®æ–‡ä»¶ä¸­è®¾ç½® slotComment
slotCopyright: | 
  <strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯
# slotArticleEnd: | 
#   <p><img src="https://i.dawnlab.me/53a8c7cf3ad77a0f0a456ce2c6afe88a.png" loading="lazy"></p>